/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.des.produit;

import gestion.des.produit.dao.ConnectDB;
import java.awt.Toolkit;
import gestion.des.produit.modele.Bashoard ;
import gestion.des.produit.modele.Stock_commande;
import java.awt.HeadlessException;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ziram
 */
public class Ajoute_command extends javax.swing.JFrame {

    /**
     * Creates new form Ajoute_command
     */
    public Ajoute_command() {
        initComponents();icon();
    }
    void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().
                getResource("Cartgrill_icon-icons.com_51191.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jTextField8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jTextField9 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();

        setTitle("Ajoute commande");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Noveau Commande");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 10, 290, 30);

        jLabel2.setText("Nom et prenom");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 60, 110, 14);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(30, 80, 440, 30);

        jLabel3.setText("Nom de profil");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 120, 180, 14);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(30, 140, 440, 30);

        jLabel4.setText("Nom de la page");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 180, 160, 14);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(30, 200, 440, 30);

        jLabel5.setText("N° téléphone");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 240, 150, 14);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(30, 260, 440, 30);

        jLabel6.setText("Budget");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 300, 110, 14);

        jTextField5.setText("0");
        jPanel1.add(jTextField5);
        jTextField5.setBounds(30, 320, 160, 30);

        jLabel7.setText("Ville");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 360, 100, 14);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(30, 380, 160, 30);

        jLabel8.setText("Groupe d'age cible");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 420, 140, 14);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(30, 440, 160, 30);

        jLabel9.setText("Sexe cible");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 480, 90, 14);

        jLabel10.setText("Type de ciblage");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 530, 180, 14);

        jButton1.setBackground(new java.awt.Color(182, 36, 110));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enregistre");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 650, 190, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Attirer les clients (messages)", "Interagir avec la publication", "Vues uniquement", "Agrandir la page (Abonnements aux page)" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(30, 550, 430, 30);

        jLabel11.setText("Le paiment a-t-il été effectue ?");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 590, 200, 14);

        jCheckBox1.setText("Oui");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(30, 610, 150, 23);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Homme");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(30, 500, 120, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Famme");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(160, 500, 120, 23);

        jDateChooser4.setForeground(new java.awt.Color(204, 255, 255));
        jDateChooser4.setDateFormatString("yyyy-MM-dd ");
        jDateChooser4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel1.add(jDateChooser4);
        jDateChooser4.setBounds(320, 600, 142, 33);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("0");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(270, 330, 130, 14);

        jLabel13.setText("Date de paiment proposée");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(180, 610, 140, 14);

        jLabel14.setText("Jours");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(360, 360, 90, 14);
        jPanel1.add(jSpinner1);
        jSpinner1.setBounds(380, 380, 90, 30);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(210, 440, 260, 30);

        jLabel15.setText("Remarque");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(200, 420, 140, 14);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/001-technology.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel17);
        jLabel17.setBounds(200, 314, 30, 40);

        jLabel18.setText("€");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(410, 330, 40, 14);

        jCheckBox2.setText("change Prix");
        jCheckBox2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox2StateChanged(evt);
            }
        });
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(110, 290, 130, 30);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(340, 290, 130, 30);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Both");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(290, 500, 120, 23);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/about2.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(0, 0, 510, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
   ConnectDB db;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      try {  
        Stock_commande ST = db.getInfocommande() ;
        Float devise = ST.getVent() ;
        Float gain = ST.getGain() ;
        
        if(jCheckBox2.isSelected()){
         devise = Float.parseFloat(jTextField9.getText());
         gain = devise - ST.getAchat() ;
        }
        DecimalFormat df = new DecimalFormat("0",DecimalFormatSymbols.getInstance(Locale.ENGLISH));
        df.setMaximumFractionDigits(2);
        jLabel12.setText(df.format((Float.parseFloat(jTextField5.getText())/devise))); 
        
     
       SimpleDateFormat sdft = new SimpleDateFormat("YYYY/MM/dd HH:mm:ss"); 
       SimpleDateFormat sdf = new SimpleDateFormat("YYYY/MM/dd"); 
       Date d = new Date();
      
       String servie = "on" ;
       String sex = "homme" ;
       String dateversement =  sdf.format(d);
       if(jRadioButton2.isSelected()){
          sex = "famme" ;
    
        }
       if(jRadioButton3.isSelected()){
          sex = "both" ;
    
        }
       if (! jCheckBox1.isSelected()){
         servie = "off" ;
         dateversement = sdf.format(jDateChooser4.getDate());
          }
        gain = gain* Float.parseFloat(jLabel12.getText()) ;
          Bashoard b = new Bashoard(jTextField1.getText(), jTextField6.getText(), (int) jSpinner1.getValue(),
                  Double.parseDouble(jLabel12.getText()), Double.parseDouble(jTextField5.getText()),
                  (String) sdft.format(d), (String) dateversement,
                  jTextField8.getText(),  jTextField4.getText(),   jTextField3.getText(),  jTextField2.getText() , 
                     servie, "Inactif", sex, (String) jComboBox1.getSelectedItem(), jTextField7.getText() , gain );
        db.Ajoute_commande(b);  
        JOptionPane.showMessageDialog(null, "La Commande est ajoute MERCIE <3");
       } catch (HeadlessException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Verefier les champes SVP!");
       }
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        // TODO add your handling code here:
               if (jCheckBox1.isSelected()){
                  jDateChooser4.setVisible(false);
                  jLabel13.setVisible(false) ;
               }
               else{
                  jDateChooser4.setVisible(true);
                  jLabel13.setVisible(true) ;
               }   
        
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        Stock_commande ST = db.getInfocommande() ;
        Float devise = ST.getVent() ;
        if(jCheckBox2.isSelected()){
         devise = Float.parseFloat(jTextField9.getText());
        
        }
        DecimalFormat df = new DecimalFormat("0",DecimalFormatSymbols.getInstance(Locale.ENGLISH));
        df.setMaximumFractionDigits(2);
        jLabel12.setText(df.format((Float.parseFloat(jTextField5.getText())/devise))); 
        
    }//GEN-LAST:event_jLabel17MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
         db=new ConnectDB();db.ConnexionIntoDataBase(); 
         jTextField9.setVisible(false);
        
    }//GEN-LAST:event_formWindowActivated

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        // TODO add your handling code here:
              if (jCheckBox1.isSelected()){
              jDateChooser4.setVisible(false);
              jLabel13.setVisible(false) ;
               }
              else{
                  jDateChooser4.setVisible(true);
                  jLabel13.setVisible(true) ;
               }
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jCheckBox2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox2StateChanged
        // TODO add your handling code here:
        
        if(jCheckBox2.isSelected()){
           jTextField9.setVisible(true);
        }else{
           jTextField9.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox2StateChanged

 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajoute_command.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajoute_command.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajoute_command.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajoute_command.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajoute_command().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
