/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.des.produit;
import gestion.des.produit.dao.ConnectDB;
import gestion.des.produit.modele.Bashoard;
import gestion.des.produit.modele.Stock_commande;
import gestion.des.produit.modele.Vente_commande;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Time;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ziram
 */
public class BashoardForm extends javax.swing.JFrame {

    /**
     * Creates new form Bashoard
     */
   public BashoardForm() {
        initComponents();icon();
    }
    void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().
                getResource("Cartgrill_icon-icons.com_51191.png")));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jDateChooser5 = new com.toedter.calendar.JDateChooser();
        jDateChooser6 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jDateChooser7 = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bashoard");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nom et prenom", "Budget", "Devise €", "Gain", "Jours", "Date insert", "Etat de commande"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(40);
        jTable1.setRowMargin(2);
        jTable1.setSelectionBackground(new java.awt.Color(182, 36, 110));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 250, 730, 340);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "Pas payé", "Terminé", "Inactif", "Actif", "Nom et prenom", "Date d'insertion", "Budget" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(20, 170, 190, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/viewmag--icone-5948-32.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(210, 170, 30, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(20, 210, 220, 30);

        jDateChooser4.setForeground(new java.awt.Color(204, 255, 255));
        jDateChooser4.setDateFormatString("yyyy-MM-dd ");
        jDateChooser4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel1.add(jDateChooser4);
        jDateChooser4.setBounds(300, 170, 142, 33);

        jDateChooser3.setForeground(new java.awt.Color(204, 255, 255));
        jDateChooser3.setDateFormatString("yyyy-MM-dd ");
        jDateChooser3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel1.add(jDateChooser3);
        jDateChooser3.setBounds(300, 210, 142, 33);

        jLabel2.setText("du:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 170, 30, 30);

        jLabel3.setText("au:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 210, 30, 30);

        jButton2.setText("Noveau Commande");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 90, 220, 60);

        jButton3.setText("Imprime");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(440, 600, 140, 40);

        jButton4.setText("Supprime");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(600, 600, 130, 40);

        jButton5.setText("Détail");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(610, 200, 130, 40);

        jButton6.setText("Rapport");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(10, 600, 110, 40);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/249fed4d5438b48059b5c68192f99327.0.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1230, 10, 110, 70);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/e6fce3aae6c8d1a33bad41079bd5c835.0.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1230, 10, 110, 80);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(182, 36, 110));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Zi Ram");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(530, 20, 290, 70);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("220 DA");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1220, 250, 120, 40);
        jPanel1.add(jSpinner1);
        jSpinner1.setBounds(1120, 190, 80, 40);
        jPanel1.add(jSpinner2);
        jSpinner2.setBounds(1120, 250, 80, 40);

        jDateChooser5.setForeground(new java.awt.Color(204, 255, 255));
        jDateChooser5.setDateFormatString("yyyy-MM-dd ");
        jDateChooser5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jDateChooser5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jDateChooser5MouseEntered(evt);
            }
        });
        jPanel1.add(jDateChooser5);
        jDateChooser5.setBounds(1200, 550, 142, 33);

        jDateChooser6.setForeground(new java.awt.Color(204, 255, 255));
        jDateChooser6.setDateFormatString("yyyy-MM-dd ");
        jDateChooser6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel1.add(jDateChooser6);
        jDateChooser6.setBounds(1000, 550, 142, 33);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("au:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1170, 550, 30, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("du:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(970, 550, 30, 30);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/viewmag--icone-5948-32.png"))); // NOI18N
        jButton7.setText("Search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(1110, 470, 140, 60);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(1020, 320, 310, 40);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/Save_icon-icons.com_73702.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(1070, 220, 40, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Rest :  200 $");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12);
        jLabel12.setBounds(1120, 640, 220, 50);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel13.setText("200 DA");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 650, 510, 19);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel14.setText("1 $");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(30, 670, 520, 19);

        jButton9.setText("Start");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(750, 290, 120, 40);

        jButton10.setText("Historique");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(750, 350, 120, 40);

        jButton11.setText("Payé");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(750, 410, 120, 40);

        jButton12.setText("Stop");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(750, 470, 120, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/2358046.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 20, 210, 50);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 102));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/Save_icon-icons.com_73702.png"))); // NOI18N
        jLabel16.setText("+");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16);
        jLabel16.setBounds(910, 640, 50, 50);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Combien Rest €");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(750, 520, 120, 20);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/002-sign.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(820, 550, 50, 30);
        jPanel1.add(jSpinner4);
        jSpinner4.setBounds(750, 550, 60, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jLabel19);
        jLabel19.setBounds(1020, 420, 310, 40);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jLabel20);
        jLabel20.setBounds(1020, 370, 310, 40);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 102));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("300 DA");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel21);
        jLabel21.setBounds(1220, 190, 120, 40);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Les gains de la semaine derniére");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(830, 50, 350, 40);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 102));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel23);
        jLabel23.setBounds(830, 140, 350, 40);

        jCheckBox1.setText("Retarde ?");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(750, 260, 120, 23);

        jDateChooser7.setForeground(new java.awt.Color(204, 255, 255));
        jDateChooser7.setDateFormatString("yyyy-MM-dd ");
        jDateChooser7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel1.add(jDateChooser7);
        jDateChooser7.setBounds(880, 260, 142, 33);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 153, 102));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel24);
        jLabel24.setBounds(830, 100, 350, 40);

        jButton14.setText("Importe Data");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(469, 200, 120, 40);

        jButton15.setText("Vide");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(140, 600, 60, 40);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(970, 640, 110, 50);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/MISe ajour.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(220, 600, 48, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/about3.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1366, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1364, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int gain = ((int)jSpinner1.getValue() - (int)jSpinner2.getValue()) ; 
        
        String sql = "Update stock_commande set vent='"+ jSpinner1.getValue()+"' , achat='"+jSpinner2.getValue()+"' , gain ='"+gain+"'  where id = '0'" ;
        db.UpdateCommand(sql);
        jSpinner1.setVisible(false);
        jSpinner2.setVisible(false);
        jButton8.setVisible(false);
        Stock_commande ST = db.getInfocommande() ;
        jLabel21.setText(ST.getVent()+" DA");
        jLabel8.setText(ST.getAchat()+" DA");
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        try{
     
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY/MM/dd"); 
        Date d = new Date();    
        int i = jTable1.getSelectedRow();
        int id = (int) jTable1.getValueAt(i, 0);
        Bashoard b = db.getDetailcommande(id);
        if("off".equals(b.getEtat_vercement())){
        String sql = "Update commande set etat_vercement='on'  where N_commande = '"+id+"'" ;
        db.UpdateCommand(sql);
        Vente_commande a = new Vente_commande( Float.parseFloat(""+jTable1.getValueAt(i, 4)), Float.parseFloat(""+jTable1.getValueAt(i, 2)), Float.parseFloat(""+jTable1.getValueAt(i, 3)),  sdf.format(d), (String) jTable1.getValueAt(i, 1));
        db.Ajoute_vente_commande(a);  
        
        }else{JOptionPane.showMessageDialog(null, "Deja servie");}
        }catch(HeadlessException | NumberFormatException e){
            JOptionPane.showMessageDialog(null, "ereur operation");
        }
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                Ajoute_command ac=new Ajoute_command();

                ac.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
       
        jDateChooser7.setVisible(false);
       // rest 
        jLabel16.setVisible(false);
        jTextField2.setVisible(false);
       // devise
        jButton8.setVisible(false);
        jSpinner1.setVisible(false);
        jSpinner2.setVisible(false);
       //stop
        jLabel18.setVisible(false);
        jSpinner4.setVisible(false);
        jButton13.setVisible(false);
       //table
         jTextField1.setVisible(false);
         jDateChooser4.setVisible(false);
         jDateChooser3.setVisible(false);
         jLabel2.setVisible(false);
         jLabel3.setVisible(false);
        db=new ConnectDB();db.ConnexionIntoDataBase();        
        jLabel5.setVisible(false);
       
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY/MM/dd"); 
        Date d = new Date();
        db.Gainweek(jLabel24 , jLabel23);
        String sql = "select * from commande where date_versment <= '"+sdf.format(d)+"' and etat_vercement = 'off'";
        
        if (db.getAllcommande(jTable1 , jLabel13 , jLabel14, sql) > 0){
            jLabel4.setVisible(false);
            jLabel5.setVisible(true);
        }
        
        DecimalFormat df = new DecimalFormat("0",DecimalFormatSymbols.getInstance(Locale.ENGLISH));
        df.setMaximumFractionDigits(2);     
        sql="select * from commande";
        db.getAllcommande(jTable1 , jLabel13 , jLabel14, sql) ;
        
        Stock_commande ST = db.getInfocommande() ;
        jSpinner1.setValue((int)ST.getVent());
        jSpinner2.setValue((int)ST.getAchat());
        jLabel21.setText(ST.getVent()+" DA");
        jLabel8.setText(ST.getAchat()+" DA");
        jLabel12.setText("Rest : "+df.format(ST.getQnt())+" €");

        sql="Update commande set etat_commande='Terminé' where etat_commande='Actif' and deadline <= '"+sdf.format(d)+"' ";
        db.UpdateCommand(sql);
        jLabel6.setText(db.Best());
    }//GEN-LAST:event_formWindowActivated

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY/MM/dd"); 
        Date d = new Date();
        String sql = "select * from commande where date_versment <= '"+sdf.format(d)+"' and etat_vercement = 'off' ";
        
        db.getAllcommande(jTable1 , jLabel13 , jLabel14, sql) ;
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String sql ;
        
        if(jComboBox1.getSelectedItem() == "ALL" || jComboBox1.getSelectedItem() == "Pas payé" || jComboBox1.getSelectedItem() == "Actif"
                || jComboBox1.getSelectedItem() == "Inactif" || jComboBox1.getSelectedItem() == "Terminé"){
         jTextField1.setVisible(false);
         jDateChooser4.setVisible(false);
         jDateChooser3.setVisible(false);
         jLabel2.setVisible(false);
         jLabel3.setVisible(false);
         if(jComboBox1.getSelectedItem() == "ALL"){
         sql="select * from commande";
         db.getAllcommande(jTable1 , jLabel13 , jLabel14, sql) ;
         }
         if(jComboBox1.getSelectedItem() == "Pas payé"){
         sql="select * from commande where etat_vercement = 'off' ";
         db.getAllcommande(jTable1 , jLabel13 , jLabel14, sql) ;}
         if(jComboBox1.getSelectedItem() == "Actif"){
         sql="select * from commande where etat_commande = 'Actif' ";
         db.getAllcommande(jTable1 , jLabel13 , jLabel14, sql) ;
         }
         if(jComboBox1.getSelectedItem() == "Inactif"){
         sql="select * from commande where etat_commande = 'Inactif' ";
         db.getAllcommande(jTable1 , jLabel13 , jLabel14, sql) ;
         }
         if(jComboBox1.getSelectedItem() == "Terminé"){
         sql="select * from commande where etat_commande = 'Terminé' ";
         db.getAllcommande(jTable1 , jLabel13 , jLabel14, sql) ;
         }
        }else if(jComboBox1.getSelectedItem() == "Budget" || jComboBox1.getSelectedItem() == "Nom et prenom"){
         jTextField1.setVisible(true);
         jDateChooser4.setVisible(false);
         jDateChooser3.setVisible(false);
         jLabel2.setVisible(false);
         jLabel3.setVisible(false);}
        else if(jComboBox1.getSelectedItem() == "Date d'insertion"){
         jTextField1.setVisible(false);
         jDateChooser4.setVisible(true);
         jDateChooser3.setVisible(true);
         jLabel2.setVisible(true);
         jLabel3.setVisible(true);}
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY/MM/dd"); 

        String sql ;
        if(jComboBox1.getSelectedItem() == "Budget"){
         sql="select * from commande where budge >= '"+jTextField1.getText()+"' ";
         db.getAllcommande(jTable1 , jLabel13 , jLabel14, sql) ;
         }
        if(jComboBox1.getSelectedItem() == "Nom et prenom"){
         sql="select * from commande where nom_prenom_client == '"+jTextField1.getText()+"' ";
         db.getAllcommande(jTable1 , jLabel13 , jLabel14, sql) ;
         }
         if(jComboBox1.getSelectedItem() == "Date d'insertion"){
         sql="select * from commande where date_insert <= '"+sdf.format(jDateChooser3.getDate())+"' and  date_insert >= '"+sdf.format(jDateChooser4.getDate()) +"' ";
         db.getAllcommande(jTable1 , jLabel13 , jLabel14, sql) ;
         }        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        int id = (int) jTable1.getValueAt(i, 0);
        Bashoard b = db.getDetailcommande(id);
        if("Actif".equals(b.getEtat_commande())){
        
        jLabel18.setVisible(true);
        jSpinner4.setVisible(true);
        jButton13.setVisible(true);
        
        }else{JOptionPane.showMessageDialog(null, "La commande n'est pas Actif");}
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        jButton8.setVisible(true);
        jSpinner1.setVisible(true);
        jSpinner2.setVisible(true);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        jButton8.setVisible(true);
        jSpinner1.setVisible(true);
        jSpinner2.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        jLabel16.setVisible(true);
        jTextField2.setVisible(true);
     
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        try {
        String sql ;
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY/MM/dd"); 
        Date d = new Date();
        int i = jTable1.getSelectedRow();
        if("Inactif".equals((String)jTable1.getValueAt(i, 7))){
       
        int id = (int) jTable1.getValueAt(i, 0);
        int jours =  (int) jTable1.getValueAt(i, 5);
        
        if(! jCheckBox1.isSelected()){
        sql = "Update commande set etat_commande='Actif' ,  deadline ='"+sdf.format(d.getTime()+(1000*60*60*24*jours))+"',date_start='" + sdf.format(d) + "' where N_commande = '"+id+"'" ;
         
        }else {
            
            Date date = jDateChooser7.getDate();
            d=date ;
            sql = "Update commande set etat_commande='Actif' ,  deadline ='"+sdf.format(date.getTime()+(1000*60*60*24*jours))+"',date_start='" + sdf.format(date) + "' where N_commande = '"+id+"'" ;
                 
        }
         db.UpdateCommand(sql);
         sql="select * from commande";
         db.getAllcommande(jTable1 , jLabel13 , jLabel14, sql) ;
        
        Stock_commande ST = db.getInfocommande() ;
        DecimalFormat df = new DecimalFormat("0",DecimalFormatSymbols.getInstance(Locale.ENGLISH));
        df.setMaximumFractionDigits(2);
        sql = "Update stock_commande set qnt='"+(ST.getQnt() - Float.parseFloat(""+jTable1.getValueAt(i, 3)) )+"'  where id = '0'" ;
        db.UpdateCommand(sql);
        ST = db.getInfocommande() ;
        jLabel12.setText("Rest : "+df.format(ST.getQnt())+" €");
        Bashoard b = db.getDetailcommande(id);
        if("on".equals(b.getEtat_vercement()))
        { 
        Vente_commande a = new Vente_commande( Float.parseFloat(""+jTable1.getValueAt(i, 4)), Float.parseFloat(""+jTable1.getValueAt(i, 2)), Float.parseFloat(""+jTable1.getValueAt(i, 3)),  sdf.format(d), (String) jTable1.getValueAt(i, 1));
        db.Ajoute_vente_commande(a);  }
        
        
        
        }else{ JOptionPane.showMessageDialog(null, "La commande est deja Actif !");}
        }catch(HeadlessException | NumberFormatException e){
            JOptionPane.showMessageDialog(null, "ereur operation");
        }
                 
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        // TODO add your handling code here:
       if(jCheckBox1.isSelected()) {
        jDateChooser7.setVisible(true);}
       else {jDateChooser7.setVisible(false);}
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        try{ 
            int i = jTable1.getSelectedRow();
            int id = (int)jTable1.getValueAt(i, 0);
            
            if(JOptionPane.showConfirmDialog(null, "confirmer la supression ?", "suppression"
            ,JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
            String sql ;
            sql ="DELETE FROM commande WHERE  	N_commande=" + id;
            db.DeleteCommande(sql);

            
        }}catch(HeadlessException | NumberFormatException e){
            JOptionPane.showMessageDialog(null, "ereur operation");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
            DecimalFormat df = new DecimalFormat("0",DecimalFormatSymbols.getInstance(Locale.ENGLISH));
            df.setMaximumFractionDigits(2);
               int i = jTable1.getSelectedRow();
               int id = (int) jTable1.getValueAt(i, 0);    
               Bashoard b = db.getDetailcommande(id);
               Detail_commande dc=new Detail_commande();
               dc.jLabel1.setText("Commande N° "+id);
               dc.jLabel24.setText(df.format(b.getBudge())+" DA");
               dc.jLabel25.setText(b.getEtat_commande());
               dc.jLabel26.setText(b.getDate_insert());
               dc.jLabel27.setText(b.getJours()+" Jours");
               dc.jLabel28.setText(b.getNote());
               dc.jLabel29.setText(df.format(b.getPrix_devise())+" €");
               dc.jLabel30.setText(b.getAge());
               dc.jLabel31.setText(b.getBut());
               dc.jLabel32.setText(b.getDate_versment());
               dc.jLabel33.setText(b.getDeadline());
               dc.jLabel34.setText(b.getDate_start());
               String dv = "Non" ;
               if("on".equals(b.getEtat_vercement())){dv = "Oui" ;}
               dc.jLabel35.setText(dv);
               dc.jLabel36.setText(b.getSex());
               dc.jLabel37.setText(b.getWilaya());
               dc.jTextField1.setText(b.getNom_prenom_client());
               dc.jTextField2.setText(b.getProfile_facebook());
               dc.jTextField3.setText(b.getPage_facebook());
               dc.jTextField4.setText(b.getTele());
               
               dc.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("0",DecimalFormatSymbols.getInstance(Locale.ENGLISH));
        df.setMaximumFractionDigits(2);
        Stock_commande ST = db.getInfocommande() ;
        
        String sql = "Update stock_commande set qnt='"+  Float.parseFloat(jTextField2.getText()) +"'  where id = '0'" ;
        db.UpdateCommand(sql);
        ST = db.getInfocommande() ;
        jLabel12.setText("Rest : "+df.format(ST.getQnt())+" €");
        jLabel16.setVisible(false);
        jTextField2.setVisible(false);
        
        
        
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        Vente_commande_form vf = new Vente_commande_form();
        vf.setVisible(true);
        
        
        
        
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         int i = jTable1.getSelectedRow();
               int id = (int) jTable1.getValueAt(i, 0);    
               Bashoard b = db.getDetailcommande(id);
               Rapport_commande dc=new Rapport_commande();
               dc.jLabel1.setText("Commande N° "+id);
               dc.jLabel24.setText(b.getBudge()+" DA");
               dc.jLabel27.setText(b.getJours()+" Jours");
               dc.jLabel30.setText(b.getAge());
               dc.jLabel31.setText(b.getBut());
               dc.jLabel33.setText(b.getDeadline());
               dc.jLabel34.setText(b.getDate_start());
               String dv = "Non" ;
               if("on".equals(b.getEtat_vercement())){dv = "Oui" ;}
               dc.jLabel36.setText(b.getSex());
               dc.jLabel37.setText(b.getWilaya());
               dc.jTextField1.setText(b.getNom_prenom_client());
               dc.jTextField2.setText(b.getProfile_facebook());
               dc.jTextField3.setText(b.getPage_facebook());
               
               dc.setVisible(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        jLabel18.setVisible(false);
        jSpinner4.setVisible(false);
        jButton13.setVisible(false);
         DecimalFormat df = new DecimalFormat("0",DecimalFormatSymbols.getInstance(Locale.ENGLISH));
        df.setMaximumFractionDigits(2);
        Stock_commande ST = db.getInfocommande() ;
        String sql = "Update stock_commande set qnt='"+ ((int) jSpinner4.getValue() + ST.getQnt())+"'  where id = '0'" ;
        db.UpdateCommand(sql);
        ST = db.getInfocommande() ;
        jLabel12.setText("Rest : "+df.format(ST.getQnt())+" €");
        
          int i = jTable1.getSelectedRow();
          int id = (int)jTable1.getValueAt(i, 0);
            
              
   
      
        sql = "Update commande set etat_commande='Stop'  where N_commande = '"+id+"'" ;
        db.UpdateCommand(sql);
        
        
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY/MM/dd"); 
        Date d = new Date();  
        float lossE = (float) (Float.parseFloat(""+jTable1.getValueAt(i, 3)) - (int) jSpinner4.getValue());
        lossE = lossE*(-1);
        float lossT = lossE*ST.getVent();
        float loss = lossE*ST.getGain();
        System.out.println(lossE);
        System.out.println(lossT);
        System.out.println(loss);
        Vente_commande a = new Vente_commande( loss, lossT, lossE,  sdf.format(d), (String) jTable1.getValueAt(i, 1));
        db.Ajoute_vente_commande(a);
            
            
            if(JOptionPane.showConfirmDialog(null, "confirmer la supression ?", "suppression"
            ,JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
            
            sql ="DELETE FROM commande WHERE  	N_commande=" + id;
            db.DeleteCommande(sql);}

        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           MessageFormat Header=new MessageFormat(db.showDateTime()+"");

        MessageFormat footer=new MessageFormat("page{0,number,integer}");
        try {

            jTable1.print(JTable.PrintMode.FIT_WIDTH, Header, footer );

        } catch (java.awt.print.PrinterException ex) {
            System.err.format("ereur dimpression",ex.getMessage());
        }

        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        db.Vente_commande(jLabel11, jLabel20, jLabel19, jDateChooser6.getDate(), jDateChooser5.getDate());
        
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
         try {
          JFileChooser file =new JFileChooser();
            file.setFileFilter(new FileNameExtensionFilter("csv file","csv"));
            file.showSaveDialog(this);
            File f = file.getSelectedFile();
            String path = f.getAbsolutePath();
            BufferedReader reader = new BufferedReader(new FileReader(path));
            BufferedReader reader2 = new BufferedReader(new FileReader(path));
            String get ;
            Stock_commande ST = db.getInfocommande() ;
            Float devise ;
            Float gain;
            Float gaine;
      
            DecimalFormat df = new DecimalFormat("0",DecimalFormatSymbols.getInstance(Locale.ENGLISH));
            df.setMaximumFractionDigits(2);
            SimpleDateFormat sdft = new SimpleDateFormat("YYYY/MM/dd HH:mm:ss"); 
            SimpleDateFormat sdf = new SimpleDateFormat("YYYY/MM/dd"); 
            Date d = new Date();
            Bashoard b ;
            reader2.readLine();
            reader.readLine();
            while( reader.readLine() !=null){
                String [] data = reader2.readLine().split(",");
                devise = ST.getVent() ;
                gain = ST.getGain() ;
               
                
                 double dev = Float.parseFloat(df.format(Float.parseFloat(data[7])))/devise; 
                 String servie = "on" ;
                 String dateversement =  sdf.format(d);
                 if ("لا".equals(data[9])){
                 servie = "off" ;
                 dateversement = sdf.format(d.getTime()+(1000*60*60*24*3));
                 }
                 
                 gaine = Float.parseFloat(df.format(gain))* Float.parseFloat(df.format(dev));

                 
                 gaine = Float.parseFloat(df.format(gaine));
                 b = new Bashoard(data[1], data[3] , Integer.parseInt(data[6]),
                   Float.parseFloat(df.format(dev)),  Double.parseDouble(data[7]),
                   sdf.format(d),  dateversement,
                   data[12], data[4],   data[5],  data[2] , 
                   servie, "Inactif",  data[11], data[8], data[10] , gaine );
                 db.Ajoute_commande(b);  
        
                
  
            }
                JOptionPane.showMessageDialog(null, "Succefull"," Done", 
                  JOptionPane.INFORMATION_MESSAGE);
            
        } catch (IOException ex) {
            Logger.getLogger(BashoardForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
                   try{   
            if(JOptionPane.showConfirmDialog(null, "confirmer l'opperation de vide tout la table de commande ?", "suppression"
            ,JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
            String sql ;
            sql ="DELETE FROM commande " ;
            db.DeleteCommande(sql);

            
        }}catch(HeadlessException | NumberFormatException e){
          JOptionPane.showMessageDialog(null, "ereur operation");
        }
        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jDateChooser5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser5MouseEntered
        // TODO add your handling code here:
  
    }//GEN-LAST:event_jDateChooser5MouseEntered

    private void jDateChooser5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        Setting st = new Setting();
        st.setVisible(true);
        
    }//GEN-LAST:event_jLabel7MouseClicked
ConnectDB db;

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bashoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bashoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bashoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bashoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BashoardForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private com.toedter.calendar.JDateChooser jDateChooser5;
    private com.toedter.calendar.JDateChooser jDateChooser6;
    private com.toedter.calendar.JDateChooser jDateChooser7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
