/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.des.produit;

import gestion.des.produit.dao.ConnectDB;
import java.awt.Toolkit;

/**
 *
 * @author ziram
 */
public class Detail_commande extends javax.swing.JFrame {

    /**
     * Creates new form Ajoute_command
     */
    public Detail_commande() {
        initComponents();icon();
    }
    void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().
                getResource("Cartgrill_icon-icons.com_51191.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setTitle("Detail commande");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Commande N°");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 10, 290, 30);

        jLabel2.setText("Nom et prenom");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 60, 110, 14);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1.setSelectionColor(new java.awt.Color(182, 36, 110));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(30, 80, 200, 30);

        jLabel3.setText("Nom de profil");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 120, 180, 14);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField2.setSelectionColor(new java.awt.Color(182, 36, 110));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(30, 140, 200, 30);

        jLabel4.setText("Nom de la page");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 180, 160, 14);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField3.setSelectionColor(new java.awt.Color(182, 36, 110));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(30, 200, 200, 30);

        jLabel5.setText("N° téléphone");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 240, 150, 14);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField4.setSelectionColor(new java.awt.Color(182, 36, 110));
        jPanel1.add(jTextField4);
        jTextField4.setBounds(30, 260, 200, 30);

        jLabel6.setText("Budget");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 300, 110, 14);

        jLabel7.setText("Ville");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 360, 100, 14);

        jLabel8.setText("Groupe d'age cible");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(300, 360, 150, 14);

        jLabel9.setText("Sexe cible");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 420, 90, 14);

        jLabel10.setText("Type de ciblage");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(300, 420, 140, 14);

        jButton1.setBackground(new java.awt.Color(182, 36, 110));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 650, 190, 40);

        jLabel11.setText("Le paiment a-t-il été effectue ?");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 480, 200, 14);

        jLabel13.setText("Date de paiment proposée");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(300, 480, 150, 14);

        jLabel14.setText("Devise");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(300, 300, 100, 14);

        jLabel15.setText("Remarque");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(300, 240, 150, 14);

        jLabel19.setText("Date de lancement la commande");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(20, 550, 180, 14);

        jLabel20.setText("Date de termine");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(300, 550, 140, 14);

        jLabel21.setText("Date d'nsertion");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(300, 120, 140, 14);

        jLabel22.setText("Etat de la commande");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(300, 60, 140, 14);

        jLabel23.setText("Jours");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(300, 180, 90, 14);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel24);
        jLabel24.setBounds(30, 320, 180, 20);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel25);
        jLabel25.setBounds(310, 80, 180, 20);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel26);
        jLabel26.setBounds(310, 140, 180, 20);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel27);
        jLabel27.setBounds(310, 200, 180, 20);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel28);
        jLabel28.setBounds(310, 260, 180, 20);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel29);
        jLabel29.setBounds(310, 320, 180, 20);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel30);
        jLabel30.setBounds(310, 380, 180, 20);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel31);
        jLabel31.setBounds(310, 440, 180, 20);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel32);
        jLabel32.setBounds(310, 500, 180, 20);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel33);
        jLabel33.setBounds(310, 570, 180, 20);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel34);
        jLabel34.setBounds(30, 570, 180, 20);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel35);
        jLabel35.setBounds(30, 500, 180, 20);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel36);
        jLabel36.setBounds(30, 440, 180, 20);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel37);
        jLabel37.setBounds(30, 380, 180, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/about2.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(0, 0, 510, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
   ConnectDB db;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        
        
         db=new ConnectDB();
         db.ConnexionIntoDataBase(); 
    }//GEN-LAST:event_formWindowActivated

 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detail_commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detail_commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detail_commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detail_commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Detail_commande().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    public javax.swing.JLabel jLabel28;
    public javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel30;
    public javax.swing.JLabel jLabel31;
    public javax.swing.JLabel jLabel32;
    public javax.swing.JLabel jLabel33;
    public javax.swing.JLabel jLabel34;
    public javax.swing.JLabel jLabel35;
    public javax.swing.JLabel jLabel36;
    public javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
