/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.des.produit;

import gestion.des.produit.dao.ConnectDB;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTable;

/**
 *
 * @author ziram
 */
public class Rapport_commande extends javax.swing.JFrame  implements Printable, ActionListener{

    /**
     * Creates new form Ajoute_command
     */
    public Rapport_commande() {
        initComponents();icon();
    }
    void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().
                getResource("Cartgrill_icon-icons.com_51191.png")));
    }
    
  
    public int print(Graphics g, PageFormat pf, int page) throws PrinterException { 
        if (page > 0) { return NO_SUCH_PAGE; } 
    ImageIcon icon = new ImageIcon("logo.png");
     Image image = icon.getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT);
     icon.setImage(image); 
     int y=0;
    Graphics2D g2d = (Graphics2D) g; 
      g2d.drawString("Welcome",100, y+= g2d.getFontMetrics().getHeight());
      g2d.drawString("",15, y+= g2d.getFontMetrics().getHeight());
      g2d.drawImage(icon.getImage(), 90 ,y+= g2d.getFontMetrics().getHeight() , icon.getImageObserver()) ; 
   
   
    
      g2d.drawString("",15, y+= g2d.getFontMetrics().getHeight());
      g2d.drawString("",15, y+= g2d.getFontMetrics().getHeight());
      g2d.drawString("",15, y+= g2d.getFontMetrics().getHeight());
      g2d.drawString("",15, y+= g2d.getFontMetrics().getHeight());
    
    g2d.drawString("=============================",15, y+= g2d.getFontMetrics().getHeight());
      g2d.drawString(jLabel1.getText(),15, y+= g2d.getFontMetrics().getHeight());
      g2d.drawString("Nom et prenom : "+jTextField1.getText(),15, y+= g2d.getFontMetrics().getHeight());
      g2d.drawString("Nom de profil : "+jTextField2.getText(),15, y+= g2d.getFontMetrics().getHeight());
      g2d.drawString("Nom de la page : "+jTextField3.getText(),15, y+= g2d.getFontMetrics().getHeight());
    
    g2d.drawString("=============================",15, y+= g2d.getFontMetrics().getHeight());
    
      g2d.drawString("Budget : "+jLabel24.getText(),15, y+= g2d.getFontMetrics().getHeight());
      g2d.drawString("Type de ciblage : "+jLabel31.getText(),15, y+= g2d.getFontMetrics().getHeight());
      g2d.drawString("Ville : "+jLabel37.getText(),15, y+= g2d.getFontMetrics().getHeight());
      g2d.drawString("Groupe d'age cible : "+jLabel30.getText(),15, y+= g2d.getFontMetrics().getHeight());
      g2d.drawString("Sexe cible :"+jLabel36.getText(),15, y+= g2d.getFontMetrics().getHeight());
      g2d.drawString("Jours : "+jLabel27.getText(),15, y+= g2d.getFontMetrics().getHeight());
      g2d.drawString("Date de lancement la commande : "+jLabel34.getText(),15, y+= g2d.getFontMetrics().getHeight());
      g2d.drawString("Date de termine : "+jLabel33.getText(),15, y+= g2d.getFontMetrics().getHeight());
      
    
    g2d.drawString("=============================",15, y+= g2d.getFontMetrics().getHeight());
      g2d.drawString("Numbre de veus : "+jTextField4.getText(),15, y+= g2d.getFontMetrics().getHeight());
      g2d.drawString("Numbre de reaction : "+jTextField5.getText(),15, y+= g2d.getFontMetrics().getHeight());
      g2d.drawString("",15, y+= g2d.getFontMetrics().getHeight());
      
      
    g2d.drawString("=============================",15, y+= g2d.getFontMetrics().getHeight());
      g2d.drawString("Tel : "+db.Tel(),15, y+= g2d.getFontMetrics().getHeight());
      g2d.drawString("Local : "+db.Addr(),15, y+= g2d.getFontMetrics().getHeight());
 

    
    //printAll(g); 
    return PAGE_EXISTS; }
    @Override
   public void actionPerformed(ActionEvent e) { 
       PrinterJob job = PrinterJob.getPrinterJob();
       job.setPrintable((Printable) this);
   
   boolean ok = job.printDialog();
   if (ok) {
       try { job.print(); }
       catch (PrinterException ex) { } }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setTitle("Rapport commande");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Commande N°");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 10, 290, 30);

        jLabel2.setText("Nom et prenom");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 80, 110, 14);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1.setSelectionColor(new java.awt.Color(182, 36, 110));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(30, 100, 200, 30);

        jLabel3.setText("Nom de profil");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 140, 180, 14);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField2.setSelectionColor(new java.awt.Color(182, 36, 110));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(30, 160, 200, 30);

        jLabel4.setText("Nom de la page");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 200, 160, 14);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField3.setSelectionColor(new java.awt.Color(182, 36, 110));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(30, 220, 200, 30);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField4.setSelectionColor(new java.awt.Color(182, 36, 110));
        jPanel1.add(jTextField4);
        jTextField4.setBounds(30, 280, 180, 30);

        jLabel6.setText("Budget");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 320, 110, 14);

        jLabel7.setText("Ville");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 380, 100, 14);

        jLabel8.setText("Groupe d'age cible");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(300, 380, 150, 14);

        jLabel9.setText("Sexe cible");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 440, 90, 14);

        jLabel10.setText("Type de ciblage");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(300, 440, 140, 14);

        jButton1.setBackground(new java.awt.Color(182, 36, 110));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Imprime");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 650, 190, 40);

        jLabel19.setText("Date de lancement la commande");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(20, 500, 180, 14);

        jLabel20.setText("Date de termine");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(300, 500, 140, 14);

        jLabel23.setText("Jours");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(300, 320, 90, 14);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel24);
        jLabel24.setBounds(30, 340, 180, 20);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel27);
        jLabel27.setBounds(310, 340, 180, 20);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel30);
        jLabel30.setBounds(310, 400, 180, 20);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel31);
        jLabel31.setBounds(310, 460, 180, 20);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel33);
        jLabel33.setBounds(310, 520, 180, 20);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel34);
        jLabel34.setBounds(30, 520, 180, 20);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel36);
        jLabel36.setBounds(30, 460, 180, 20);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(182, 36, 110));
        jPanel1.add(jLabel37);
        jLabel37.setBounds(30, 400, 180, 20);

        jLabel5.setText("Numbre de veus");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 260, 170, 14);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField5.setSelectionColor(new java.awt.Color(182, 36, 110));
        jPanel1.add(jTextField5);
        jTextField5.setBounds(310, 280, 180, 30);

        jLabel11.setText("Numbre de reaction");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(300, 260, 150, 14);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/about2.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(0, 0, 510, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
   ConnectDB db;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          actionPerformed(evt) ;
   
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        
        
         db=new ConnectDB();db.ConnexionIntoDataBase();
        
    }//GEN-LAST:event_formWindowActivated

 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rapport_commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rapport_commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rapport_commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rapport_commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rapport_commande().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel30;
    public javax.swing.JLabel jLabel31;
    public javax.swing.JLabel jLabel33;
    public javax.swing.JLabel jLabel34;
    public javax.swing.JLabel jLabel36;
    public javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
